### Get All Users
GET http://localhost:3000/api/users/

### Get User By ID
GET http://localhost:3000/api/users/1

### Register User
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "username": "Schilip Fauer Der Zweite",
  "password": "QgT"
}

### Login User SUCCESS
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "Schilip Fauer",
  "password": "QgT"
}

### Login User FAILURE
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "Schilip Fauer",
  "password": "AAAAAAAAA"
}

### Delete User
DELETE http://localhost:3000/api/users/1

### Get All Collections By UserID
GET http://localhost:3000/api/collections/getAll/1

### Get Collection By ID
GET http://localhost:3000/api/collections/1

### Insert Collection
POST http://localhost:3000/api/collections/
Content-Type: application/json

{
  "collectionname": "MyCollection",
  "avgspeed": null,
  "bestspeed": null,
  "wordamount": 0,
  "userid": 1
}

### Update Collection
PUT http://localhost:3000/api/collections/1
Content-Type: application/json

{
  "collectionname": "BRANDNEWCollection",
  "avgspeed": null,
  "bestspeed": null,
  "wordamount": 0,
  "userid": 1,
  "entries": [
    {
      "word": "asdasd",
      "answer": "answerrrr"
    },
    {
      "word": "2nd word",
      "answer": "2nd answer"
    },
    {
      "word": "WMC",
      "answer": "lieblingsfach"
    }
  ]
}

### Delete Collection
DELETE http://localhost:3000/api/collections/3